// packages/react/src/components/Slider.tsx
import React, { useEffect, useState } from 'react'
import  './Slider.scss'
import arrowRight from '../assets/right.svg'
import arrowLeft from '../assets/left.svg'

interface SliderProps {
  slides: {
    image: string;
    label: string;
    paragraph: string;
  }[]
}
  
export const Slider: React.FC<SliderProps> = ({slides}) => {
  const [currentSlideId, setCurrentSlideId] = useState<number>(0)
  const [slideDirection, setSlideDirection] = useState<string>('')
  const [downX, setDownX] = useState(1)
  const [upX, setUpX] = useState(1)

  const slideLeft = () => {
    setSlideDirection('left')
    if (currentSlideId > 0) {
      setCurrentSlideId(prev => prev - 1)
    } else {
      setCurrentSlideId(slides.length - 1)
    }
  }

  const slideRight = () => {
    setSlideDirection('right')
    if (currentSlideId < slides.length - 1) {
      setCurrentSlideId(prev => prev + 1)
    } else {
      setCurrentSlideId(0)
    }
  }

  const listenToMouseDown = (e: React.MouseEvent) => {
    setDownX(e.clientX)
  }

  const listenToTouchStart = (e: React.TouchEvent) => {
    setDownX(e.touches[0].clientX)
  }

  const listenToMouseUp = (e: React.MouseEvent) => {
    setUpX(e.clientX)
  }

  const listenToTouchEnd = (e: React.TouchEvent) => {
    setUpX(e.changedTouches[0].clientX)
  }

  useEffect(() => {
    if (downX + 100 < upX) {
      slideLeft()
    } else if (downX - 100 > upX) {
      slideRight()
    }
  }, [upX])

  return (
    <div 
      className="container"
      onMouseDown={(e) => listenToMouseDown(e)}
      onMouseUp={(e) => listenToMouseUp(e)}
      onTouchStart={(e => listenToTouchStart(e))}
      onTouchEnd={(e => listenToTouchEnd(e))}
    >
      <div className="slider">
        {slides.map((slide, idx) => (
          <div 
            key={slide.image}
            style={{backgroundImage: `url(${slide.image})`}}
            className={`slide ${currentSlideId === idx ? '' : slideDirection === 'right' ? 'hideToLeft' : 'hideToRight'}`} 
          >
            <h1>{slide.label}</h1>
            <p>{slide.paragraph}</p>
          </div>
        ))}
        <button className="slideButton" onClick={slideLeft}>
        <img src={arrowLeft} alt="left" className="arrow" />
        </button>
        <div className="middleSection" id="slider">
          {slides.map((slide, id) => (
            <div key={id} className={`circle ${id === currentSlideId ? 'current' : ''}`}>
            </div>
          ))}
        </div>
        <button className="slideButton" onClick={slideRight}>
          <img src={arrowRight} alt="right" className="arrow" />
        </button>
      </div>
    </div>
  );
}

// src/lib/slider/slider.component.ts
import { Component, Input, OnInit } from '@angular/core';

export interface Slide {
  label: string;
  paragraph?: string;
  image: string;
}

@Component({
  selector: 'sol-slider',
  templateUrl: 'slider.component.html',
  styleUrls: ['slider.component.scss'],
})
export class SliderComponent implements OnInit {
  constructor() {}

  @Input()
  slides: Slide[] = [];
  slideDirection: string = '';
  currentSlideId: number = 0;
  downX: number = 1;
  upX: number = 1;

  slideLeft() {
    this.slideDirection = 'left';
    if (this.currentSlideId > 0) {
      this.currentSlideId -= 1;
    } else {
      this.currentSlideId = this.slides.length - 1;
    }
  }

  slideRight() {
    this.slideDirection = 'right';
    if (this.currentSlideId < this.slides.length - 1) {
      this.currentSlideId += 1;
    } else {
      this.currentSlideId = 0;
    }
  }

  gesturedSlide() {
    if (this.downX + 100 < this.upX) {
      this.slideLeft();
    } else if (this.downX > this.upX + 100) {
      this.slideRight();
    }
  }

  listenToMousedown(e: MouseEvent) {
    this.downX = e.clientX;
  }

  listenToMouseup(e: MouseEvent) {
    this.upX = e.clientX;
    this.gesturedSlide();
  }

  listenToTouchstart(e: TouchEvent) {
    this.downX = e.touches[0].clientX;
  }

  listenToTouchend(e: TouchEvent) {
    this.upX = e.changedTouches[0].clientX;
    this.gesturedSlide();
  }

  ngOnInit(): void {}
}

<div
  class="slider"
  (mousedown)="listenToMousedown($event)"
  (mouseup)="listenToMouseup($event)"
  (touchstart)="listenToTouchstart($event)"
  (touchend)="listenToTouchend($event)"
>
  <div
    class="slider__slide-container"
    [ngStyle]="{
      transform: 'translateX(calc(-100% * ' + currentSlideId + '))'
    }"
  >
    <div
      class="slider__slide"
      *ngFor="let slide of slides; let i = index"
      [ngStyle]="{ 'background-image': 'url(' + slide.image + ')' }"
    >
      <h1>{{ slide.label }}</h1>
      <p>{{ slide.paragraph }}</p>
    </div>
  </div>

  <div class="slider__dot-navigation">
    <div
      *ngFor="let slide of slides; let i = index"
      class="slider__dot"
      [ngClass]="currentSlideId === i ? 'slider__dot--active' : ''"
      (click)="currentSlideId = i"
    ></div>
  </div>

  <button class="slider__btn slider__btn--left" (click)="slideLeft()">
    <img src="./icons/arrow-left.svg" alt="left" />
  </button>
  <button class="slider__btn slider__btn--right" (click)="slideRight()">
    <img src="./icons/arrow-right.svg" alt="right" />
  </button>
</div>
