// packages/react/src/components/Slider.tsx
import React, { useEffect, useState } from 'react'
import  './Slider.scss'
import arrowRight from '../assets/right.svg'
import arrowLeft from '../assets/left.svg'

interface SliderProps {
  slides: {
    image: string;
    label: string;
    paragraph: string;
  }[]
}
  
export const Slider: React.FC<SliderProps> = ({slides}) => {
  const [currentSlideId, setCurrentSlideId] = useState<number>(0)
  const [slideDirection, setSlideDirection] = useState<string>('')
  const [downX, setDownX] = useState(1)
  const [upX, setUpX] = useState(1)

  const slideLeft = () => {
    setSlideDirection('left')
    if (currentSlideId > 0) {
      setCurrentSlideId(prev => prev - 1)
    } else {
      setCurrentSlideId(slides.length - 1)
    }
  }

  const slideRight = () => {
    setSlideDirection('right')
    if (currentSlideId < slides.length - 1) {
      setCurrentSlideId(prev => prev + 1)
    } else {
      setCurrentSlideId(0)
    }
  }

  const listenToMouseDown = (e: React.MouseEvent) => {
    setDownX(e.clientX)
  }

  const listenToTouchStart = (e: React.TouchEvent) => {
    setDownX(e.touches[0].clientX)
  }

  const listenToMouseUp = (e: React.MouseEvent) => {
    setUpX(e.clientX)
  }

  const listenToTouchEnd = (e: React.TouchEvent) => {
    setUpX(e.changedTouches[0].clientX)
  }

  useEffect(() => {
    if (downX + 100 < upX) {
      slideLeft()
    } else if (downX - 100 > upX) {
      slideRight()
    }
  }, [upX])

  return (
    <div 
      className="container"
      onMouseDown={(e) => listenToMouseDown(e)}
      onMouseUp={(e) => listenToMouseUp(e)}
      onTouchStart={(e => listenToTouchStart(e))}
      onTouchEnd={(e => listenToTouchEnd(e))}
    >
      <div className="slider">
        {slides.map((slide, idx) => (
          <div 
            key={slide.image}
            style={{backgroundImage: `url(${slide.image})`}}
            className={`slide ${currentSlideId === idx ? '' : slideDirection === 'right' ? 'hideToLeft' : 'hideToRight'}`} 
          >
            <h1>{slide.label}</h1>
            <p>{slide.paragraph}</p>
          </div>
        ))}
        <button className="slideButton" onClick={slideLeft}>
        <img src={arrowLeft} alt="left" className="arrow" />
        </button>
        <div className="middleSection" id="slider">
          {slides.map((slide, id) => (
            <div key={id} className={`circle ${id === currentSlideId ? 'current' : ''}`}>
            </div>
          ))}
        </div>
        <button className="slideButton" onClick={slideRight}>
          <img src={arrowRight} alt="right" className="arrow" />
        </button>
      </div>
    </div>
  );
}

// packages/vue/src/components/Slider.vue
<script setup lang="ts">
import { ref, toRef } from 'vue'

const props = defineProps({
  slides: {
    type: Array,
  }
})

const slidesRef = toRef(props, 'slides')

const activeSlideId = ref(0)
const slideDirection = ref('')
const downX = ref(1)
const upX = ref(1)

function slideLeft() {
  slideDirection.value = 'left'
  if (activeSlideId.value > 0) {
    activeSlideId.value --
  } else {
    activeSlideId.value = slidesRef.value.length - 1
  }
}

function slideRight() {
  slideDirection.value = 'right'
  if (activeSlideId.value < slidesRef.value.length - 1) {
    activeSlideId.value ++
  } else {
    activeSlideId.value = 0
  }
}

function gesturedSlide() {
  if (downX.value + 100 < upX.value) {
    slideLeft();
  } else if (downX.value > upX.value + 100) {
    slideRight();
  }
}

function listenToMouseDown(e: MouseEvent) {
  console.log('yo')
  downX.value = e.clientX
}

function listenToMouseUp(e: MouseEvent) {
  upX.value = e.clientX
  gesturedSlide()
}

const listenToTouchStart = (e: TouchEvent) => {
  downX.value = e.touches[0].clientX
}

const listenToTouchEnd = (e: TouchEvent) => {
  upX.value = e.changedTouches[0].clientX
  gesturedSlide()
}

</script>

<template>
   <div class="container" v-if="slidesRef"
    @mousedown="listenToMouseDown"
    @mouseup="listenToMouseUp"
    @touchstart="listenToTouchStart"
    @touchend="listenToTouchEnd"
   >
      <div class='slider'>
        <div 
          class="slide"
          v-for="(slide, idx) in slidesRef"
          :key="slide.label"
          :style="{ backgroundImage: `url(${slide.image})` }"
          :class="{
            hideToLeft: slideDirection === 'right' && activeSlideId !== idx, 
            hideToRight: slideDirection === 'left' && activeSlideId !== idx
          }"
        >
          <h1>{{slide.label}}</h1>
          <p>{{slide.paragraph}}</p>
        </div>
        <button class='slideButton' @click="slideLeft()">
          <img src='../assets/left-icon.svg' alt="" class='arrow' />
        </button>
        <div class='middleSection' id="slider">
            <div v-bind:key="slide.label" v-for="(slide, index) in slidesRef" class='circle' :class="{current: index === activeSlideId}">
            </div>
        </div>
        <button class='slideButton' @click="slideRight()">
          <img src='../assets/right-icon.svg' alt="" class='arrow' />
        </button>
      </div>
    </div>
</template>

<style lang="scss" scoped>
.container {
  width: 100vw;
  height: 500px;
  display: flex;
  justify-content: center;
  align-items: center;
  position: relative;
  overflow-x: hidden;
  touch-action: none;
}

.slider {
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: space-between;
  align-items: center;
  overflow: hidden;

  .slide {
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
    width: 100%;
    height: 100%;
    position: absolute;
    background-position: center;
    background-size: cover;
    pointer-events: none;

    &.hideToRight {
      z-index: 1;
      transition: 1s;
      visibility: hidden;
      transform: translateX(100%);
    }

    &.hideToLeft {
      z-index: 1;
      transition: 1s;
      visibility: hidden;
      transform: translateX(-100%);
    }
  }

  .slideButton {
    width: 10%;
    height: 100%;
    background-color: transparent;
    border: none;
    cursor: pointer;
    display: flex;
    justify-content: center;
    align-items: center;
    transition: 0.5s;
    z-index: 5;

    &:hover {
      background-color: #fff;
      opacity: 0.3;
    }

    .arrow {
      width: 30px;
      height: 30px;
      display: flex;
      justify-content: center;
      align-items: center;
    }
  }

  .middleSection {
    height: 100%;
    display: flex;
    justify-content: center;
    align-items: flex-end;
    flex-grow: 1;
    z-index: 10;
  }
}

.circle {
  width: 10px;
  height: 10px;
  background-color: gray;
  border-radius: 10px;
  margin: 10px;

  &.current {
    background-color: white;
  }
}

h1,
p {
  color: #fff;
}
</style>
